name: viz
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas 
  - vtk
  - vedo
  - graphviz
  - python-graphviz
  - matplotlib 
  - notebook 
  - nb_conda_kernels
  - folium
  - statsmodels=0.13.2
  - pymc3
  - theano-pymc
  - mkl
  - mkl-service
  - glob2
  - skikit-learn
  - pip:
    - pylint
    - pyan3
    - pandoc
    - beautifulsoup4
    - requests
    - lxml
