name: viz
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas 
  - vtk
  - vedo
  - graphviz
  - python-graphviz
  - matplotlib 
  - notebook 
  - nb_conda_kernels
  - folium
  - pip:
    - pylint
    - pyan3
    - pandoc
    - beautifulsoup4
    - requests
    - lxml
